name: '📝 Documentation Request'
description: Create a new issue for a new documentation request
title: 'docs: <title>'
labels: ['documentation']
body:
  - type: markdown
    attributes:
      value: |
        Provide a general summary of the issue in the Title above
  - type: textarea
    id: expected-behavior
    attributes:
      label: 'Expected Documentation'
      description: Tell us what you need
      placeholder: Short and explicit description of your request...
    validations:
      required: true
  - type: textarea
    id: current-behavior
    attributes:
      label: 'Current Documentation'
      description: Explain the difference from current documentation
    validations:
      required: false
  - type: textarea
    id: possible-solution
    attributes:
      label: 'Possible Solution'
      description: Ideas about how to write the requested documentation
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: 'Context'
      description: |
        How has this issue affected you? What are you trying to accomplish?
        Providing context helps us come up with a solution that is most useful in the real world
    validations:
      required: false